package application;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.control.TextField;
import javafx.stage.Stage;
import javafx.scene.Parent;
import javafx.scene.Scene;
import java.io.IOException;

import javax.swing.JOptionPane;

import javafx.scene.Node;
import javafx.event.ActionEvent;
import javafx.scene.control.PasswordField;

public class landingPageUIController {
	private Stage stage;
	private Scene scene;
	private Parent root;
	public String usrname;
	public String usrpass;
	@FXML
	private TextField usernameField;
	@FXML
	private PasswordField passwordField;

	// Event Listener on Button.onAction
	@FXML
	public void loginButtonPress(ActionEvent event) throws IOException{
		// TODO Autogenerated
		usrname = usernameField.getText();
		usrpass = passwordField.getText();
		 UserCredentials userCredentials = UserCredentials.getInstance();
		System.out.println(usrname + " "+ usrpass);
		if(usrname.equals(userCredentials.getUsername()) && usrpass.equals(userCredentials.getPassword())){
			FXMLLoader loader = new FXMLLoader(getClass().getResource("verifiedPageUI.fxml"));
			root = loader.load();
			verifiedPageUIController VerifiedPageUIController = loader.getController();
			stage = (Stage)((Node)event.getSource()).getScene().getWindow();
			scene = new Scene(root);
			stage.setScene(scene);
			stage.show();
			
		
		}
		else {
			JOptionPane.showMessageDialog(null, "Invalid ID or Password!");
			usernameField.clear();
			passwordField.clear();
			
			
		}
		
	}
	// Event Listener on Button.onAction
	@FXML
	public void signUpButtonPress(ActionEvent event) throws IOException{
		// TODO Autogenerated
		FXMLLoader loader = new FXMLLoader(getClass().getResource("registerPageUI.fxml"));
		root = loader.load();
		registerPageUIController RegisterPageUIController = loader.getController();
		stage = (Stage)((Node)event.getSource()).getScene().getWindow();
		scene = new Scene(root);
		stage.setScene(scene);
		stage.show();
	}
}
