package application;

import javafx.fxml.FXML;

import javafx.scene.control.TextField;

import javafx.fxml.FXMLLoader;
import javafx.scene.control.TextField;
import javafx.stage.Stage;
import javafx.scene.Parent;
import javafx.scene.Scene;
import java.io.IOException;

import javax.swing.JOptionPane;

import javafx.scene.Node;
import javafx.event.ActionEvent;
import javafx.scene.control.PasswordField;
import javafx.event.ActionEvent;

import javafx.scene.control.PasswordField;

public class registerPageUIController {
	private Stage stage;
	private Scene scene;
	private Parent root;
	
	public String Newemail;
	public String NewConfirmPass;
	public String NewuserName;
	public String NewuserPass;
	
	@FXML
	private TextField usernameField;
	@FXML
	private PasswordField passwordField;
	@FXML
	private PasswordField confirmPasswordField;
	@FXML
	private TextField emailField;

	// Event Listener on Button.onAction
	@FXML
	public void pressSignUpButton(ActionEvent event) throws IOException {
		// TODO Autogenerated
		Newemail = emailField.getText();
		NewConfirmPass = confirmPasswordField.getText();
		NewuserName = usernameField.getText();
		NewuserPass = passwordField.getText();
		if (NewuserName.isEmpty() || NewuserPass.isEmpty()) {
	        JOptionPane.showMessageDialog(null, "Please fill all the details!");
	        return; // Do not proceed further
	    }
		UserCredentials userCredentials = UserCredentials.getInstance();
        userCredentials.setUsername(NewuserName);
        userCredentials.setPassword(NewuserPass);
		FXMLLoader loader = new FXMLLoader(getClass().getResource("verifiedPageUI.fxml"));
		root = loader.load();
		verifiedPageUIController VerifiedPageUIController = loader.getController();
		stage = (Stage)((Node)event.getSource()).getScene().getWindow();
		scene = new Scene(root);
		stage.setScene(scene);
		stage.show();
	}
}
